name: hw-int
version: '0.0.0.3'
synopsis: Integers
description: Please see README.md
category: Data
author: John Ky
maintainer: newhoggy@gmail.com
copyright: 2016 John Ky
license: BSD3
github: haskell-works/hw-int
homepage: http://github.com/haskell-works/hw-int#readme
tested-with: GHC == 8.6.3, GHC == 8.4.4, GHC == 8.2.2, GHC == 8.0.2
stability: Stable

extra-source-files:
- README.md

ghc-options:
- -Wall
- -O2

dependencies:
- base >=4 && <5

library:
  source-dirs: src

tests:
  hw-prim-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - QuickCheck          >= 2.10       && < 2.12
    - hedgehog            >= 0.5        && < 0.7
    - hspec               >= 2.4        && < 2.6
    - hw-hspec-hedgehog   >= 0.1        && < 0.2
    - hw-prim
    verbatim:
      build-tool-depends: hspec-discover:hspec-discover
